# An alternative to POSTMAN in VSCode. Use via REST Client by Huachao Mao in VS Code Extension Library
POST http://localhost:5000/api/login/newAccount
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "username": "johndoe",
  "password": "password",
  "isAdmin": false
}

### <- new requests are seperated by 3 hash symbols